version: 2.1

orbs:
  codacy: codacy/base@0.3.3

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - codacy/checkout_and_version:
          write_sbt_version: true
      - codacy/sbt:
          name: populate_cache
          cmd: |
            sbt ";set scalafmtUseIvy in ThisBuild := false;update"
          requires:
            - codacy/checkout_and_version
      - codacy/sbt:
          name: check_fmt
          cmd: sbt ";scalafmt::test;test:scalafmt::test;sbt:scalafmt::test"
          requires:
            - populate_cache
      - codacy/sbt:
          name: compile
          cmd: sbt +compile
          requires:
            - populate_cache
      - codacy/sbt:
          name: test
          cmd: sbt +test
          requires:
            - compile
      - codacy/sbt:
          name: publish
          context: CodacyAWS
          cmd: |
            sbt ";retrieveGPGKeys;+publishSigned;sonatypeReleaseAll"
          requires:
            - test
          filters:
            branches:
              only:
                - master
      - codacy/tag_version:
          name: tag_version
          context: CodacyAWS
          requires:
            - publish
          filters:
            branches:
              only:
                - master
